# Dockerfile.prod
FROM node:22-alpine AS build

WORKDIR /app
COPY . .

RUN corepack enable && corepack prepare pnpm@10 --activate
RUN pnpm install
RUN pnpm run build:prod

FROM nginx:alpine
COPY --from=build /app/dist/docker-example/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 4200
